[package]
name = "testing-utils"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
irys-storage.workspace = true
eyre.workspace = true
irys-types.workspace = true
rand.workspace = true

[lints]
workspace = true
