[package]
edition = "2021"
name = "irys-chain"
version = "0.1.0"


[dependencies]
# Irys
irys-database.workspace = true
irys-storage.workspace = true
irys-c.workspace = true
irys-reth-node-bridge.workspace = true
irys-types.workspace = true
irys-api-server.workspace = true
irys-config.workspace = true
irys-testing-utils.workspace = true
irys-actors.workspace = true
irys-packing.workspace = true
irys-vdf.workspace = true
#

base64-url.workspace = true
awc = "3.5.1"
base58 = "0.2.0"
assert_matches = "1.5.0"
clap = "4.5.20"
eyre = "0.6.8"
openssl.workspace = true
rand = "0.8.5"
rand_chacha = "0.3.1"
nodit.workspace = true
reth-codecs-derive.workspace = true
reth-codecs.workspace = true
reth-db-api.workspace = true
reth-db-models.workspace = true
reth-db.workspace = true
reth-primitives.workspace = true
reth.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
sha2 = "0.10.8"
tempfile = "3.10"
env_logger = "0.11.5"
actix-rt.workspace = true
actix-web.workspace = true
actix-http.workspace = true
jsonrpsee.workspace = true
reth-e2e-test-utils.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

alloy-network = { path = "../../ext/alloy/crates/network" }
alloy-signer-local.workspace = true
alloy-core.workspace = true
actix.workspace = true
alloy-rlp.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-serde.workspace = true
arbitrary = { workspace = true, features = [
	"derive",
] } # arbitrary.workspace = truebytes.workspace = true
bytes.workspace = true

derive_more.workspace = true
modular-bitfield.workspace = true
reth-cli-runner.workspace = true
test-fuzz.workspace = true
futures-util.workspace = true
futures.workspace = true
reth-tracing.workspace = true
hex.workspace = true
k256 = { version = "0.13", default-features = false, features = [
	"ecdsa",
	"serde",
] }
alloy-sol-macro = { workspace = true, features = ["json"] }
alloy-sol-types.workspace = true
alloy-contract.workspace = true
alloy-provider.workspace = true
[[bin]]
name = "irys"
path = "src/main.rs"
