[package]
edition = "2021"
name = "irys-packing"
version = "0.1.0"

[dependencies]
irys-c.workspace = true
irys-primitives.workspace = true
irys-types.workspace = true
eyre.workspace = true
rand.workspace = true