[package]
name = "irys-storage"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
nodit.workspace = true
eyre.workspace = true
serde.workspace = true
irys-types.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
actix-rt = "2.10.0"
actix.workspace = true
bytes.workspace = true
futures.workspace = true
serde_json.workspace = true
[lints]
workspace = true
