[package]
name = "database"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre = "0.6.2"
assert_matches.workspace = true
reth.workspace = true
tokio.workspace = true
reth-db.workspace = true
arbitrary = { workspace = true, features = ["derive"] }
serde = { workspace = true, version = "1.0", features = ["derive"] }
serde_json.workspace = true
reth-db-api.workspace = true
bytes.workspace = true
modular-bitfield.workspace = true
reth-codecs.workspace = true
eyre.workspace = true
irys-types.workspace = true
test-fuzz.workspace = true
tempfile.workspace = true

[lints]
workspace = true
