[package]
edition = "2021"
name = "irys-efficient-sampling"
version = "0.1.0"

[dependencies]
irys-types.workspace = true

eyre.workspace = true
rand.workspace = true
assert_matches.workspace = true
openssl.workspace = true
tracing.workspace = true
arbitrary.workspace = true