name: "Setup Repo Action"
description: "A reusable composite action that setups rust and other common tasks"

runs:
  using: "composite"
  steps:
    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: "rustfmt,clippy,cargo,llvm-tools-preview"
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        cache-all-crates: true
        rust-cache: "buildjet" # allows for fast cache compresson & restoration on self-hosted runners
