use alloy_evm::precompiles::{DynPrecompile, PrecompileInput};
use alloy_sol_types::SolCall as _;
use irys_types::precompile::PD_PRECOMPILE_ADDRESS;
use reth_evm::precompiles::PrecompilesMap;
use revm::precompile::PrecompileError;
use revm::precompile::{PrecompileOutput, PrecompileResult};
use revm::primitives::hardfork::SpecId;
use std::borrow::Cow;
use tracing::{debug, warn};

use crate::instructions::pd_return_marker::{clear_pd_return_marker, set_pd_return_marker};
use crate::precompiles::pd::constants::PD_BASE_GAS_COST;
use crate::precompiles::pd::error::{PdPrecompileError, try_encode_as_revert};
use crate::precompiles::pd::functions::{readBytesCall, readDataCall};
use crate::precompiles::pd::read_bytes::read_chunk_data;
use crate::precompiles::pd::utils::parse_pd_specifiers;

use super::context::PdContext;

/// Programmable Data precompile implementation.
///
/// Dispatches on 4-byte ABI selectors generated by `alloy_sol_types::sol!`.
/// Parameters are ABI-decoded, return values are ABI-encoded (`bytes memory`),
/// and user-facing errors are returned as ABI-encoded custom error reverts.
#[inline]
fn pd_precompile(pd_context: PdContext) -> DynPrecompile {
    (move |input: PrecompileInput<'_>| -> PrecompileResult {
        // Clear any stale marker from a previous CALL/STATICCALL in this tx.
        clear_pd_return_marker();

        let data = input.data;
        let gas_limit = input.gas;
        debug!(
            data_len = data.len(),
            gas_limit = gas_limit,
            "PD precompile called"
        );

        // Minimum 4 bytes for ABI selector
        if data.len() < 4 {
            warn!("PD precompile: insufficient input data, len={}", data.len());
            return Err(PdPrecompileError::InsufficientInput {
                expected: 4,
                actual: data.len(),
            }
            .into());
        }

        if PD_BASE_GAS_COST > gas_limit {
            warn!(
                base_cost = PD_BASE_GAS_COST,
                gas_limit = gas_limit,
                "PD precompile: insufficient gas for base cost"
            );
            return Err(PrecompileError::OutOfGas);
        }

        let access_list = pd_context.read_access_list();
        if access_list.is_empty() {
            warn!("PD precompile: transaction missing required access list");
            return Err(PdPrecompileError::MissingAccessList.into());
        }

        let chunk_config = pd_context.chunk_config();
        let specifiers = parse_pd_specifiers(&access_list, &chunk_config).map_err(|e| {
            warn!(error = ?e, "PD precompile: failed to parse access list");
            PdPrecompileError::InvalidAccessList {
                reason: e.to_string(),
            }
        })?;

        let selector: [u8; 4] = data[..4].try_into().expect("length checked >= 4 above");

        debug!(?selector, "PD precompile: decoded selector");

        let result = match selector {
            readDataCall::SELECTOR => {
                let decoded = readDataCall::abi_decode_raw(&data[4..]).map_err(|e| {
                    warn!(error = %e, "PD precompile: readData ABI decode error");
                    PrecompileError::Other(Cow::Owned(format!("ABI decode error: {e}")))
                })?;
                let spec = specifiers.get(decoded.index as usize).ok_or(
                    PdPrecompileError::SpecifierNotFound {
                        index: decoded.index,
                        available: specifiers.len(),
                    },
                )?;
                debug!(index = decoded.index, "PD precompile: readData");
                read_chunk_data(spec, spec.byte_off, spec.len, &pd_context)
            }
            readBytesCall::SELECTOR => {
                let decoded = readBytesCall::abi_decode_raw(&data[4..]).map_err(|e| {
                    warn!(error = %e, "PD precompile: readBytes ABI decode error");
                    PrecompileError::Other(Cow::Owned(format!("ABI decode error: {e}")))
                })?;
                let spec = specifiers.get(decoded.index as usize).ok_or(
                    PdPrecompileError::SpecifierNotFound {
                        index: decoded.index,
                        available: specifiers.len(),
                    },
                )?;
                debug!(
                    index = decoded.index,
                    offset = decoded.offset,
                    length = decoded.length,
                    "PD precompile: readBytes"
                );
                read_chunk_data(spec, decoded.offset, decoded.length, &pd_context)
            }
            _ => {
                warn!(?selector, "PD precompile: unknown selector");
                return Err(PrecompileError::Other(
                    "PD precompile: unknown function selector".into(),
                ));
            }
        };

        match result {
            Ok(bytes) => {
                // ABI-encode the return value: abi.encode(bytes memory data)
                let encoded: alloy_primitives::Bytes =
                    readDataCall::abi_encode_returns(&bytes).into();

                // Record this allocation as the PD return marker so that the
                // custom RETURNDATACOPY handler can identify it by pointer
                // identity and skip memory expansion gas.
                set_pd_return_marker(&encoded);

                debug!(
                    gas_used = PD_BASE_GAS_COST,
                    bytes_returned = encoded.len(),
                    "PD precompile: execution successful"
                );

                Ok(PrecompileOutput::new(PD_BASE_GAS_COST, encoded))
            }
            Err(e) => {
                // Try to encode as ABI custom error revert
                if let Some(reverted) = try_encode_as_revert(&e, PD_BASE_GAS_COST) {
                    debug!(error = %e, "PD precompile: returning ABI-encoded revert");
                    Ok(reverted)
                } else {
                    warn!(error = %e, "PD precompile: internal error");
                    Err(e.into())
                }
            }
        }
    })
    .into()
}

/// Registers the PD precompile at address 0x500.
#[inline]
pub fn register_irys_precompiles_if_active(
    precompiles: &mut PrecompilesMap,
    spec: SpecId,
    pd_context: PdContext,
) {
    // Only install when Frontier or later is active as per hardfork schedule.
    if spec >= SpecId::FRONTIER {
        precompiles.apply_precompile(&PD_PRECOMPILE_ADDRESS, |_current| {
            Some(pd_precompile(pd_context))
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::evm::{IRYS_USD_PRICE_ACCOUNT, IrysEvmFactory};
    use alloy_eips::eip2930::AccessList;
    use alloy_evm::{Evm as _, EvmFactory as _};
    use alloy_primitives::{Address, B256, Bytes};
    use dashmap::DashMap;
    use irys_types::range_specifier::{PdAccessListArgsTypeId, PdDataRead, encode_pd_fee};
    use reth_evm::EvmEnv;
    use revm::context::{BlockEnv, CfgEnv, TxEnv};
    use revm::database::CacheDB;
    use revm::database_interface::EmptyDB;
    use revm::primitives::{TxKind, U256, hardfork::SpecId};
    use revm::state::AccountInfo;
    use std::sync::Arc;

    /// Fixed test caller address used across all PD precompile tests so the
    /// CacheDB can be pre-seeded with sufficient balance for PD fee deduction.
    const TEST_CALLER: Address = Address::repeat_byte(0x42);

    /// Large fee value that exceeds the minimum PD transaction cost threshold
    /// configured in the testing hardfork config (0.01 USD at 1e18 scale).
    /// Using 1 IRYS (1e18) per chunk ensures the min-cost check always passes.
    const TEST_FEE_PER_CHUNK: u128 = 1_000_000_000_000_000_000;

    /// Appends PD fee keys (PdPriorityFee + PdBaseFeeCap) to an existing access list
    /// that targets `PD_PRECOMPILE_ADDRESS`. Required because the EVM layer validates
    /// PD transactions via `parse_pd_transaction()`, which rejects access lists
    /// missing fee parameters.
    fn with_test_fees(access_list: AccessList) -> AccessList {
        let fee = U256::from(TEST_FEE_PER_CHUNK);
        let mut items = access_list.0;
        if let Some(pd_item) = items
            .iter_mut()
            .find(|i| i.address == PD_PRECOMPILE_ADDRESS)
        {
            pd_item.storage_keys.push(B256::from(
                encode_pd_fee(PdAccessListArgsTypeId::PdPriorityFee as u8, fee)
                    .expect("test fee encoding"),
            ));
            pd_item.storage_keys.push(B256::from(
                encode_pd_fee(PdAccessListArgsTypeId::PdBaseFeeCap as u8, fee)
                    .expect("test fee encoding"),
            ));
        }
        AccessList(items)
    }

    /// Creates a `CacheDB` pre-seeded with accounts required by the PD fee
    /// validation path in `transact_raw`:
    /// - `IRYS_USD_PRICE_ACCOUNT` with a non-zero balance ($1.00 in 1e18 scale)
    /// - `TEST_CALLER` with a large balance to cover PD fee deductions
    fn test_db() -> CacheDB<EmptyDB> {
        let mut db = CacheDB::new(EmptyDB::default());
        // IRYS/USD price = $1.00 (1e18 scale)
        db.insert_account_info(
            *IRYS_USD_PRICE_ACCOUNT,
            AccountInfo {
                balance: U256::from(1_000_000_000_000_000_000_u128),
                ..Default::default()
            },
        );
        // Fund the test caller with a very large balance so PD fee deduction
        // does not fail even for tests with many chunks (e.g., 1000 chunks * 1e18)
        db.insert_account_info(
            TEST_CALLER,
            AccountInfo {
                balance: U256::MAX / U256::from(2),
                ..Default::default()
            },
        );
        db
    }

    /// Creates a ChunkDataIndex pre-populated with zero-filled chunks for offsets 0..num_chunks.
    /// Chunk size is 32 bytes, matching `ConsensusConfig::testing()`.
    fn test_chunk_data_index(num_chunks: u64) -> irys_types::chunk_provider::ChunkDataIndex {
        let index = Arc::new(DashMap::new());
        let chunk = Arc::new(bytes::Bytes::from(vec![0_u8; 32]));
        for offset in 0..num_chunks {
            index.insert((0_u32, offset), chunk.clone());
        }
        index
    }

    /// Creates a default TxEnv for testing PD precompile.
    fn tx_env_default(data: Bytes, access_list: AccessList) -> TxEnv {
        TxEnv {
            caller: TEST_CALLER,
            kind: TxKind::Call(PD_PRECOMPILE_ADDRESS),
            nonce: 0,
            gas_limit: 30_000_000,
            value: U256::ZERO,
            data,
            gas_price: 0,
            chain_id: Some(1),
            gas_priority_fee: None,
            access_list,
            blob_hashes: Vec::new(),
            max_fee_per_blob_gas: 0,
            tx_type: 1,
            authorization_list: Default::default(),
        }
    }

    /// Helper to execute PD precompile with given input and access list.
    fn execute_precompile(
        input: Vec<u8>,
        access_list: AccessList,
        num_chunks: u64,
    ) -> revm::context::result::ResultAndState {
        let chunk_data_index = test_chunk_data_index(num_chunks);
        let factory = IrysEvmFactory::new_for_testing(chunk_data_index);

        let mut cfg_env = CfgEnv::default();
        cfg_env.spec = SpecId::CANCUN;
        cfg_env.chain_id = 1;

        let block_env = BlockEnv {
            gas_limit: 30_000_000,
            basefee: 0,
            ..Default::default()
        };

        let mut evm = factory.create_evm(test_db(), EvmEnv { cfg_env, block_env });

        let tx = tx_env_default(input.into(), access_list);

        evm.transact_raw(tx).unwrap()
    }

    /// Build a PD access list with a single data read specifier and test fees.
    fn build_test_access_list(spec: &PdDataRead) -> AccessList {
        use alloy_eips::eip2930::AccessListItem;
        with_test_fees(AccessList(vec![AccessListItem {
            address: PD_PRECOMPILE_ADDRESS,
            storage_keys: vec![B256::from(spec.encode())],
        }]))
    }

    /// Encode a `readData(index)` call using ABI encoding.
    fn encode_read_data(index: u8) -> Vec<u8> {
        let call = readDataCall { index };
        call.abi_encode()
    }

    /// Encode a `readBytes(index, offset, length)` call using ABI encoding.
    fn encode_read_bytes(index: u8, offset: u32, length: u32) -> Vec<u8> {
        let call = readBytesCall {
            index,
            offset,
            length,
        };
        call.abi_encode()
    }

    #[test]
    fn pd_precompile_read_full_byte_range() {
        let spec = PdDataRead {
            partition_index: 0,
            start: 0,
            len: 100,
            byte_off: 0,
        };

        let access_list = build_test_access_list(&spec);
        // chunks_needed = ceil(100/32) = 4 (chunk_size=32 in testing config)
        let result = execute_precompile(encode_read_data(0), access_list, 4);
        assert!(result.result.is_success(), "transaction should succeed");

        let min_expected_gas = PD_BASE_GAS_COST;
        assert!(
            result.result.gas_used() >= min_expected_gas,
            "Gas used ({}) should be at least {} (base)",
            result.result.gas_used(),
            PD_BASE_GAS_COST
        );

        let out = result
            .result
            .into_output()
            .expect("successful result should have output");

        // Output is ABI-encoded `bytes memory`, so it has a 32-byte offset + 32-byte length prefix
        // Decode and check the actual data
        let decoded =
            readDataCall::abi_decode_returns(&out).expect("should decode ABI return value");
        assert_eq!(decoded.len(), 100, "should return 100 bytes of data");
        assert!(
            decoded.iter().all(|&b| b == 0),
            "placeholder bytes should be zero"
        );
    }

    #[test]
    fn test_insufficient_input_data() {
        let chunk_data_index = test_chunk_data_index(0);
        let factory = IrysEvmFactory::new_for_testing(chunk_data_index);
        let mut cfg_env = CfgEnv::default();
        cfg_env.spec = SpecId::CANCUN;
        let block_env = BlockEnv::default();
        let mut evm = factory.create_evm(test_db(), EvmEnv { cfg_env, block_env });

        let input = Bytes::from(vec![0, 0, 0]); // Only 3 bytes (need at least 4 for selector)
        let tx = tx_env_default(input, AccessList::default());

        let result = evm.transact_raw(tx).unwrap();
        assert!(
            !result.result.is_success(),
            "should fail with insufficient input data"
        );
    }

    #[test]
    fn test_read_partial_byte_range() {
        // chunk_size=32, num_chunks_in_partition=10 in testing config.
        // Request 320 bytes total (10 chunks), then read a partial range.
        let spec = PdDataRead {
            partition_index: 0,
            start: 0,
            len: 320,
            byte_off: 0,
        };

        let access_list = build_test_access_list(&spec);

        // readBytes(index=0, offset=50, length=100)
        let input = encode_read_bytes(0, 50, 100);

        // chunks_needed = ceil(320/32) = 10
        let result = execute_precompile(input, access_list, 10);
        assert!(result.result.is_success(), "readBytes should succeed");

        let min_expected_gas = PD_BASE_GAS_COST;
        assert!(
            result.result.gas_used() >= min_expected_gas,
            "Gas used should include precompile costs"
        );

        let out = result
            .result
            .into_output()
            .expect("successful result should have output");
        let decoded =
            readDataCall::abi_decode_returns(&out).expect("should decode ABI return value");
        assert_eq!(decoded.len(), 100, "should return 100 bytes");
    }

    #[test]
    fn test_no_access_list() {
        let chunk_data_index = test_chunk_data_index(0);
        let factory = IrysEvmFactory::new_for_testing(chunk_data_index);
        let mut cfg_env = CfgEnv::default();
        cfg_env.spec = SpecId::CANCUN;
        let block_env = BlockEnv::default();
        let mut evm = factory.create_evm(test_db(), EvmEnv { cfg_env, block_env });

        let input = Bytes::from(encode_read_data(0));
        let tx = tx_env_default(input, AccessList::default()); // Empty access list

        let result = evm.transact_raw(tx).unwrap();
        assert!(
            !result.result.is_success(),
            "should fail with no access list"
        );
    }

    #[test]
    fn test_invalid_function_selector() {
        let spec = PdDataRead {
            partition_index: 0,
            start: 0,
            len: 100,
            byte_off: 0,
        };

        let access_list = build_test_access_list(&spec);

        // chunks_needed = ceil(100/32) = 4
        let chunk_data_index = test_chunk_data_index(4);
        let factory = IrysEvmFactory::new_for_testing(chunk_data_index);
        let mut cfg_env = CfgEnv::default();
        cfg_env.spec = SpecId::CANCUN;
        let block_env = BlockEnv::default();
        let mut evm = factory.create_evm(test_db(), EvmEnv { cfg_env, block_env });

        let input = Bytes::from(vec![0xDE, 0xAD, 0xBE, 0xEF]); // Unknown selector
        let tx = tx_env_default(input, access_list);

        let result = evm.transact_raw(tx).unwrap();
        assert!(
            !result.result.is_success(),
            "should fail with unknown function selector"
        );
    }

    #[test]
    fn test_moderate_chunks() {
        // chunk_size=32, num_chunks_in_partition=10 in testing config.
        // Request 7 chunks worth of data (224 bytes).
        let spec = PdDataRead {
            partition_index: 0,
            start: 0,
            len: 224,
            byte_off: 0,
        };

        let access_list = build_test_access_list(&spec);

        // chunks_needed = ceil(224/32) = 7
        let result = execute_precompile(encode_read_data(0), access_list, 7);
        assert!(
            result.result.is_success(),
            "transaction should succeed with moderate chunks"
        );

        let min_expected_gas = PD_BASE_GAS_COST;
        assert!(
            result.result.gas_used() >= min_expected_gas,
            "Gas used ({}) should be at least {}",
            result.result.gas_used(),
            min_expected_gas
        );
    }

    #[test]
    fn test_zero_len_rejected() {
        // PdDataRead with len=0 is rejected at decode time, so we can't even
        // construct a valid access list key for it. This tests that the
        // precompile rejects the invalid access list.
        use alloy_eips::eip2930::AccessListItem;

        // Manually construct a key with len=0 (type byte 0x01 but len field = 0)
        let mut key = [0_u8; 32];
        key[0] = 0x01; // type byte
        // partition_index=0 at [1..9] (already zero)
        // start=0 at [9..13] (already zero)
        // len=0 at [13..17] (already zero)
        // byte_off=0 at [17..20] (already zero)

        let access_list = with_test_fees(AccessList(vec![AccessListItem {
            address: PD_PRECOMPILE_ADDRESS,
            storage_keys: vec![B256::from(key)],
        }]));

        let chunk_data_index = test_chunk_data_index(0);
        let factory = IrysEvmFactory::new_for_testing(chunk_data_index);
        let mut cfg_env = CfgEnv::default();
        cfg_env.spec = SpecId::CANCUN;
        cfg_env.chain_id = 1;
        let block_env = BlockEnv::default();
        let mut evm = factory.create_evm(test_db(), EvmEnv { cfg_env, block_env });

        let input = Bytes::from(encode_read_data(0));
        let tx = tx_env_default(input, access_list);

        // Zero-len PdDataRead is rejected at access list parse time
        let result = evm.transact_raw(tx);
        // The transaction should either error or revert
        if let Ok(r) = result {
            assert!(
                !r.result.is_success(),
                "zero-len specifier should not succeed"
            );
        }
        // Err case also acceptable — rejected at EVM layer
    }

    #[test]
    fn test_max_partition_chunks_no_overflow() {
        // chunk_size=32, num_chunks_in_partition=10 in testing config.
        // Request exactly the maximum: 10 chunks (320 bytes).
        let spec = PdDataRead {
            partition_index: 0,
            start: 0,
            len: 320,
            byte_off: 0,
        };

        let access_list = build_test_access_list(&spec);

        // chunks_needed = ceil(320/32) = 10
        let result = execute_precompile(encode_read_data(0), access_list, 10);
        assert!(
            result.result.is_success(),
            "transaction should succeed with max partition chunks"
        );

        let min_expected_gas = PD_BASE_GAS_COST;
        assert!(
            result.result.gas_used() >= min_expected_gas,
            "Gas used ({}) should be at least {}",
            result.result.gas_used(),
            min_expected_gas
        );
    }
}
