[package]
name = "irys-macros"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
toml.workspace = true

[lints]
workspace = true
