[package]
edition = "2021"
name = "irys-reth-node-bridge"
version = "0.1.0"

[dependencies]
# rustler = {version = "0.32.1", features = ["nif_version_2_17"]}
# reth = {git = "https://github.com/paradigmxyz/reth" }

# alloy-eips = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9b" }
# alloy-rpc-types-engine = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9b" }
# alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9b" }

alloy-eips.workspace = true
alloy-rpc-types.workspace = true

alloy-signer-local.workspace = true
irys-primitives.workspace = true
reth-chainspec.workspace = true
reth-cli-commands.workspace = true
reth-cli-runner.workspace = true
reth-cli-util.workspace = true
reth-cli.workspace = true
reth-db.workspace = true
reth-ethereum-cli.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-node-ethereum.workspace = true
reth-node-metrics.workspace = true
reth.workspace = true

reth-auto-seal-consensus.workspace = true
# reth-basic-payload-builder.workspace = true
reth-beacon-consensus.workspace = true
# reth-cli-runner.workspace = true
# reth-codecs.workspace = true
# reth-config.workspace = true
reth-consensus.workspace = true
# reth-db.workspace = true
# reth-db-common.workspace = true
reth-e2e-test-utils.workspace = true
# reth-evm.workspace = true
reth-exex.workspace = true
# reth-interfaces.workspace = true
reth-consensus-debug-client.workspace = true
reth-engine-service.workspace = true
reth-ethereum-engine-primitives.workspace = true

reth-engine-tree.workspace = true
reth-engine-util.workspace = true

reth-blockchain-tree.workspace = true
reth-network-api.workspace = true
reth-network.workspace = true
reth-node-api.workspace = true
reth-payload-primitives.workspace = true

reth-rpc-eth-types.workspace = true
reth-tasks.workspace = true
reth-transaction-pool.workspace = true
# reth-node-core.workspace = true
reth-node-events.workspace = true
# reth-payload-builder.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
# reth-revm.workspace = true
reth-rpc-engine-api.workspace = true
# reth-rpc-types.workspace = true
# reth-stages.workspace = true
# reth-static-file.workspace = true
reth-tracing.workspace = true
# reth-transaction-pool.workspace = true

foldhash.workspace = true
irys-types.workspace = true
reth-tokio-util.workspace = true
tracing.workspace = true

alloy-primitives.workspace = true
futures.workspace = true
irys-api-server.workspace = true
revm-primitives.workspace = true
revm.workspace = true

# alloy-rlp = "0.3.5"
bs58 = "0.5.1"
clap = "4.5.4"
eyre = "0.6.12"
futures-util.workspace = true
# jsonrpsee = { version = "0.22", features = ["client", "macros", "server"] }
jsonrpsee = { version = "0.24", features = ["client", "macros", "server"] }
jsonrpsee-core = "0.24"
jsonrpsee-http-client = "0.24"
jsonrpsee-types = "0.24"
new_type = "0.4.1"
once_cell = "1.19.0"
patch-crate = "0.1.9"
serde = "1.0.203"
serde_json = "1.0.117"
serde_path_to_error = "0.1"
strum = "0.26.3"
thiserror = "1.0.61"
tikv-jemallocator = "^0.6.0"
tokio = "1.37.0"
tokio-stream = "0.1.15"

[features]
default = ["jemalloc"]
jemalloc = []
