block_time = 30
difficulty_adjustment_interval = 2000
max_difficulty_adjustment_factor = 4.0
min_difficulty_adjustment_factor = 0.1
chunk_size = 32
num_chunks_in_partition = 6
num_chunks_in_recall_range = 2
vdf_reset_frequency = 1200
vdf_parallel_verification_thread_limit = 4
num_checkpoints_in_vdf_step = 25
vdf_sha_1s = 530_000
entropy_packing_iterations = 1000
irys_chain_id = 69727973
capacity_scalar = 100
num_blocks_in_epoch = 100
submit_ledger_epoch_length = 5
num_partitions_per_slot = 1
num_writes_before_sync = 1
persist_data_on_restart = true
num_confirmations_for_finality = 6
max_data_txs_per_block = 100
mining_key = "0xf57554aff54acd4cfaa084f45a7062d5869c8dbb789f7d6a883fade660960303"