block_time = 20
difficulty_adjustment_interval = 2000
max_difficulty_adjustment_factor = 4.0
min_difficulty_adjustment_factor = 0.1
chunk_size = 262_144
num_chunks_in_partition = 51_872_000
num_chunks_in_recall_range = 800
vdf_reset_frequency = 1200
vdf_parallel_verification_thread_limit = 4
num_checkpoints_in_vdf_step = 25
vdf_sha_1s = 100_000
entropy_packing_iterations = 1000
irys_chain_id = 1270
capacity_scalar = 100
num_blocks_in_epoch = 100
submit_ledger_epoch_length = 5
num_partitions_per_slot = 1
num_writes_before_sync = 1
persist_data_on_restart = true
max_data_txs_per_block = 100
chunk_migration_depth = 1
mining_key = "f57554aff54acd4cfaa084f45a7062d5869c8dbb789f7d6a883fade660960303"
num_capacity_partitions = 0
port = 8080
