name: Rust Checks

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  gate:
    name: gate
    runs-on: self-hosted
    if: |
      github.ref == 'refs/heads/master' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '#run-ci')
    steps:
      - name: No-op gate
        run: |
          echo "Gate conditions met"
          true

  cargo-test:
    name: cargo test
    runs-on: self-hosted
    needs: gate
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo
      - uses: taiki-e/install-action@nextest

      - name: cargo test
        run: RUST_LOG=debug cargo xtask test

  cargo-check:
    name: cargo check
    runs-on: self-hosted
    needs: gate
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo check
        run: cargo xtask check -- --all-features

  cargo-fmt:
    name: cargo fmt
    runs-on: self-hosted
    needs: gate
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo fmt
        run: cargo xtask fmt --check-only

  cargo-clippy:
    name: cargo clippy
    runs-on: self-hosted
    needs: gate
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo clippy
        run: cargo xtask clippy -- --all-features

  cargo-doc:
    name: cargo doc
    runs-on: self-hosted
    needs: gate
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo doc
        run: cargo xtask doc -- --all-features

  cargo-unused-deps:
    name: cargo unused-deps
    runs-on: self-hosted
    needs: gate
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo unused deps
        run: cargo xtask unused-deps

  typos:
    runs-on: self-hosted
    needs: gate
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.29.7
        with:
          files: .
